### ISSUE TITLE
0.6.3 todo items

### ISSUE THREAD

**Issue by artcg** [sanic-org/sanic-openapi#215]
0.6.3 todo items:

- [x] add sanic 21.3 to test environment and iron out any compatibility issues that might occur (@artcg)
- [x] change naming of oas3/ import exposing locations (@astagi did you want to do this?)
- [x] preparing docs for readthedocs -- @astagi  looking at it

next weekend would be a fine target from my end

future todo items:
-  better openapi validation across the board
- better testing / typing
-  add docstring parser to oas3
-  components / security support in oas3

**Comment by astagi** [comment]
hey @artcg I can take care of renaming no problem! Next week is ok for me!

**Comment by ahopkins** [comment]
I will not be available to roll out the version next Sunday. But, Monday (2021-03-29) works for me.

**Comment by astagi** [comment]
@artcg @ahopkins what about using '0.7.0' as release version? I think we should consider the next release more of a minor version than a patch.

**Comment by artcg** [comment]
Anything is fine with me, I think ahopkins also was interested to switching to calendar versioning (so 21.3.0 for march 21)
